---

- name: Create a new file
  hosts: nodes
  tasks:

    - name: Change file ownership, group, and permissions
      ansible.builtin.file:
        path: /tmp/example2
        owner: root
        group: root
        mode: '0644'
        state: touch

    - name: Bad remove file 
      ansible.builtin.shell: mv /tmp/example2 /tmp/example3

    - name: Change file ownership, group, and permissions
      ansible.builtin.file:
        path: /tmp/example3
        mode: '700'

    - name: Bad remove file 
      ansible.builtin.shell: mv /tmp/example3 /tmp/example2