[scraper_servers]
# Add your VM IP here after terraform apply
# Example: 34.123.45.67 ansible_user=ansible

[scraper_servers:vars]
ansible_python_interpreter=/usr/bin/python3
ansible_ssh_common_args='-o StrictHostKeyChecking=no'
